#

pluginName = QLStyle Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_QLStyle_type = QL Style
_UI_QuestionCustomization_type = Question Customization
_UI_Group_type = Group
_UI_QLStyleElement_type = Element
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_QLStyle_form_feature = Form
_UI_QLStyle_elements_feature = Elements
_UI_QuestionCustomization_helpText_feature = Help Text
_UI_QuestionCustomization_widget_feature = Widget
_UI_Group_name_feature = Name
_UI_Group_description_feature = Description
_UI_Group_layout_feature = Layout
_UI_Group_elements_feature = Elements
_UI_Unknown_feature = Unspecified

_UI_Widget_Textfield_literal = Textfield
_UI_Widget_Checkbox_literal = Checkbox
_UI_Widget_Select_literal = Select
_UI_Widget_Slider_literal = Slider
_UI_Widget_Radio_literal = Radio
_UI_GroupLayout_Vertical_literal = Vertical
_UI_GroupLayout_Horizontal_literal = Horizontal
_UI_QuestionCustomization_question_feature = Question
_UI_Widget_Date_literal = Date
